name: qu

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.8
  - numpy>=1.19
  - scikit-image>=0.17
  - scikit-learn>=0.24
  - scipy>=1.6
  - h5py>=2.10
  - cudatoolkit=10.2
  - cudnn>=7.6
  - pytorch::pytorch>=1.8
  - pytorch::ignite>=0.4
  - pytorch::torchvision>=0.9
  - pytorch::torchaudio>=0.8
  - pip>=21.0
  - natsort>=7.1
  - tifffile>=2021.3.5
  - tqdm>=4.59
  - pip:
      - pyqt5==5.12.3
      - monai[all]
      - napari[all]
      - opencv-python>=4.5.*
      - opencv-contrib_python>=4.5.*
      - albumentations>=0.5
      - conda-lock
